### ISSUE TITLE
PhoneInput can't be styled from blueprint 

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#21]
I can't for the life of me workout how to get `PhoneInput` serving styles to portal from blueprint. 

Need to:

- [ ] Style phone input appropriately with theme etc in blueprint. Looks like lots of unneeded styles there now .... ? 
- [ ] Remove temp styles from portal. // These aren't perfect but they make it work. Currently hard to control internal styles compiled vi JS
- [ ] Update portal with PhoneInput loading styles from blueprint 

Objective would be to use the same on the website ...

**Comment by mischacolley** [comment]
@lulen11 @davidpaley we use this one a lot in our projects so we should work out how to style it appropriately in blueprint so we can leverage it ... what are the blockers?

**Comment by davidpaley** [comment]
Actually we had a lot of problems trying to integrate the PhoneInput component working properly into blueprint. We couldn't accomplish this with @kbardi yet.

**Comment by mischacolley** [comment]
@davidpaley wanna detail the issues so they can be worked through? Then we could work out if we need to look at another solution or not ...

**Comment by lulen11** [comment]
hey @kbardi I've just gone in to update this phoneInput component but when I switch back to master a lot of the styles look v outdated to where they were at on the table branch. I am thinking there may need to be a merge. Wanna call me when you can? Thank you!

**Comment by lulen11** [comment]
Is this still an issue @kbardi ?

**Comment by kbardi** [comment]
Hey team, I'm working on this issue today...it is still an issue but we understood we weren't using this component at this moment, so it wasn't a priority, but now it is a priority because we need it in a couple of pages. So I'll try to get it fixed today @lulen11 @camposcristianeze @mischacolley @davidpaley

**Comment by kbardi** [comment]
I fixed the phone input on Blueprint, but I'm not sure which styles should I add...I'll check how is it working on Portal

**Comment by lulen11** [comment]
hey @kbardi how did you go on this? want me to pick it back up?

**Comment by kbardi** [comment]
Hey @lulen11 , It is working well, and I think it looks well, but I didn't style it at all, so maybe we can talk about this tomorrow in our call, and check which changes should we add to make it look better

**Comment by camposcristianeze** [comment]
bump. :) @rin @bronz3beard you both seem to have some tailwind when it comes to implementing something new (like intercom!) so if you do some research and wanna try anything here we might solve a bunch of issues in the near future 👍

**Comment by lulen11** [comment]
Just a note: I did end up styling this: http://blueprint.aimementoring.com/#phoneinput So not sure if wwe're onto a new unrelated issue now

**Comment by camposcristianeze** [comment]
@lulen11 As far as I understand we're not using Blueprint for this component as when we try to import it there are some compatibility errors we were never able to solve with this library. So if you style it here it won't be reflected in Portal. At least that is what I understood but maybe @davidpaley and @rin can confirm?

**Comment by davidpaley** [comment]
> ere never able to sol

Actually I need to make some tests because now Kevin is using another library for the phone input component in Blueprint. However the thing is I need to make a refactor to start using this new Phoneinput component from Blueprint in Portal. I am planning to do this after the release as it is something that has an impact in different things and it is quite a big change.

**Comment by kbardi** [comment]
Hi there, I'm back 😁
I added a different component for PhoneInput and it is working, because we are using it with the new architecture on the website...the thing is probably it only has styles for rainbow theme (website theme) and it has no styles for purple theme...so probably that is the error you see...
Not sure where is the problem @camposcristianeze but I can work on it if you want..

**Comment by mischacolley** [comment]
@davidpaley I'm assuming with the work you have been doing with the phone input we'll be able to remove some of the double styles and close this soon?

**Comment by davidpaley** [comment]
> @davidpaley I'm assuming with the work you have been doing with the phone input we'll be able to remove some of the double styles and close this soon?

That is correct. I am still working around the phone input in blueprint and Portal..

**Comment by rin** [comment]
@davidpaley Now that the new phone input is in Blueprint, can we check if we still have this problem?

**Comment by davidpaley** [comment]
We don't have this issue anymore. What we have now is: maybe we could improve the styles that we currently have with the new Phone Input of Blueprint in the different parts of the Portal. We should review that together @lulen11. However, we can close this one :)
