### ISSUE TITLE
[Proposed] Agreements / Terms & Conditions Component 

### ISSUE THREAD

**Issue by mischacolley** [aimementoring/blueprint#59]
**Why is this component a good candidate for Blueprint?**
Instead of unnecessarily getting someone to download and sign a PDF "Child Protection Agreement" etc I want us to explore what this might look like as a more repeatable component that's more like an agreement checkbox that allows you to review the terms you are agreeing to. 

**Describe the solution you'd like**
Something like some of the ideas here https://www.termsfeed.com/blog/add-i-agree-terms-checkbox/

**Comment by mischacolley** [comment]
@charliemckenzie has now done a Wireframe (design pending) and we wanna replace this type of thing:

<img width="631" alt="Screenshot 2019-07-29 10 48 14" src="https://user-images.githubusercontent.com/608225/62015384-7385eb80-b1ee-11e9-84ad-05b6ec0418b8.png">

with this: 

<img width="770" alt="Screenshot 2019-07-29 10 46 03" src="https://user-images.githubusercontent.com/608225/62015358-391c4e80-b1ee-11e9-8f29-321d9d47fa44.png">

And then in the new wireframes/designs @charliemckenzie is doing for Hooded Scholar Recruitment etc we'll utilise this component for other agreements like the Mentor Agreement and policies. 

The component should support: 

- Title
- Intro / paragraph text 
- Scrollable content area 
- Agreement checkbox

**Comment by mischacolley** [comment]
@charliemckenzie @davidpaley @camposcristianeze @kbardi can I get a 👍🏼so we can mark this as `component-dev-ready` and it can be built

**Comment by camposcristianeze** [comment]
> The component should support setting:
> 
> A title
> Optional intro / paragraph text
> Agreement content in a scrollable area
> The title of the agreement checkbox
> Nice to have: Support different agreement content based on country

Agreed! Especially on the base ideas for the field support settings! Two additions I'm thinking...

One addition to `Agreement content in a scrollable area`. For me this should just be a link/id to a file. This is because I think it's really important to include an integration with some Content Creation Tool. Policies tend to change very often and I don't think a maintainable component would include tightening this to a new deployment every time there's a change. 

I reviewed current policies and they were written into Google Docs.. Here are some ideas:

- Get the content from a Google Doc API: This would be the best approach, because instead of making the RIPE team change their approach, they can keep doing what they do and just give us a link. But the most complicated, it seems we would need a backend code(something like lambda functions could work!) because of some privacy considerations with Google. This will also involve a Basic template to follow for Agreements/Policies, etc.

- Migrate all of them to a Github Repo: Github is not that complicated for content creation and the RIPE Team might be able to manage things there and their API is way easier to integrate, and could be integrated from the frontend.

- Contentful: This might be part of a bigger picture so I won't do it there just yet.

A second addition is to either include in the `Agreement content in a scrollable area` or outside it a "Changelog" so people can track the additions to the policy or the agreement, and which version they agreed and what changed. This would also help us to be more transparent :).



I was also looking for some Terms and Conditions Creator API but couldn't find anything. Here are my findings:
- https://nordicapis.com/a-humans-guide-to-drafting-api-platform-policy/
- https://www.termsfeed.com/blog/api-terms-conditions/ Another article from the same place!

**Comment by davidpaley** [comment]
I think we could close this issue for now @kbardi @camposcristianeze

**Comment by camposcristianeze** [comment]
Let's get a review from either @charliemckenzie or @mischacolley as they were the ones proposing the component.

**Comment by kbardi** [comment]
Duplicated by #61
